# Generated by Django 3.1 on 2020-08-19 00:55

from django.db import migrations, models
import drummachine.models


class Migration(migrations.Migration):

    dependencies = [
        ('drummachine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('path', models.FilePathField(path=drummachine.models.sounds_path)),
            ],
        ),
    ]
