# Generated by Django 3.1 on 2020-09-04 22:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drummachine', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rack',
            unique_together={('user', 'name')},
        ),
    ]
