# Generated by Django 3.1 on 2020-08-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drummachine', '0002_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='name',
            field=models.CharField(default='untitled', max_length=25),
        ),
    ]
