# Generated by Django 3.1 on 2020-08-20 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drummachine', '0003_rack_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.RenameField(
            model_name='rack',
            old_name='instruments',
            new_name='config',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='path',
        ),
        migrations.AddField(
            model_name='instrument',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrument',
            name='kit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='drummachine.kit'),
            preserve_default=False,
        ),
    ]
